"""TDD Test Suite for POS-SaaS Superadmin Platform Console & Tenant Management."""

from __future__ import annotations

import sqlalchemy as sa
from fastapi.testclient import TestClient
from restaurant_os import models
from restaurant_os.database import get_session
from restaurant_os.main import app
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool


def _client_with_db() -> TestClient:
    engine = sa.create_engine(
        "sqlite+pysqlite://",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    models.metadata.create_all(engine)
    TestingSessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)

    def override_get_session():
        session = TestingSessionLocal()
        try:
            yield session
        finally:
            session.close()

    app.dependency_overrides[get_session] = override_get_session
    return TestClient(app)


def _login_superadmin(client: TestClient) -> dict[str, str]:
    resp = client.post(
        "/api/v1/auth/login",
        json={"email": "admin@possaas.com", "password": "admin123"},
    )
    assert resp.status_code == 200, f"Superadmin login failed: {resp.text}"
    data = resp.json()
    assert data["user"]["is_superadmin"] is True
    token = data["token"]
    return {"Authorization": f"Bearer {token}"}


def test_superadmin_auth_and_metrics() -> None:
    client = _client_with_db()
    headers = _login_superadmin(client)

    # Fetch SaaS metrics
    resp = client.get("/api/v1/superadmin/metrics", headers=headers)
    assert resp.status_code == 200
    metrics = resp.json()

    assert "total_tenants" in metrics
    assert "active_tenants" in metrics
    assert "mrr_cents" in metrics
    assert "total_orders" in metrics


def test_non_superadmin_forbidden() -> None:
    client = _client_with_db()

    # Normal tenant signs up
    signup_resp = client.post(
        "/api/v1/auth/signup",
        json={
            "business_name": "Fonda Doña Rosa",
            "owner_name": "Rosa López",
            "email": "rosa@fondarosa.com",
            "password": "Password123!",
            "business_type": "general",
        },
    )
    assert signup_resp.status_code == 201
    user_token = signup_resp.json()["token"]
    user_headers = {"Authorization": f"Bearer {user_token}"}

    # Attempt to access superadmin endpoint with ordinary user token
    resp = client.get("/api/v1/superadmin/tenants", headers=user_headers)
    assert resp.status_code == 403
    assert resp.json()["detail"]["code"] == "superadmin_forbidden"


def test_superadmin_create_tenants_with_different_menu_modes() -> None:
    client = _client_with_db()
    headers = _login_superadmin(client)

    # 1. Tenant with starter catalog generated by business_type
    resp_starter = client.post(
        "/api/v1/superadmin/tenants",
        headers=headers,
        json={
            "business_name": "Pizzería Nápoles",
            "owner_name": "Marco Rossi",
            "email": "marco@napoles.com",
            "phone": "5511223344",
            "business_type": "pizzeria",
            "plan": "starter_349",
            "menu_mode": "generate_by_type",
        },
    )
    assert resp_starter.status_code == 201
    napoles_data = resp_starter.json()
    assert napoles_data["tenant"]["plan"] == "starter_349"
    assert napoles_data["products_count"] >= 3

    # 2. Tenant with blank catalog (client wants to start clean)
    resp_blank = client.post(
        "/api/v1/superadmin/tenants",
        headers=headers,
        json={
            "business_name": "Café Minimal",
            "owner_name": "Ana Blanco",
            "email": "ana@minimal.com",
            "phone": "5522334455",
            "business_type": "cafeteria",
            "plan": "pro_599",
            "menu_mode": "blank",
        },
    )
    assert resp_blank.status_code == 201
    blank_data = resp_blank.json()
    assert blank_data["products_count"] == 0

    # 3. Tenant with AI Menu Import from structured or raw menu text
    menu_sample = """
    PIZZAS ARTESANALES
    Pizza Margarita - $180 - Salsa de tomate, mozzarella fresca y albahaca
    Pizza Cuatro Quesos - $220 - Mozzarella, gorgonzola, parmesano y gouda

    BEBIDAS
    Cerveza Artesanal - $75 - IPA local 355ml
    Agua Mineral - $35
    """
    resp_ai = client.post(
        "/api/v1/superadmin/tenants",
        headers=headers,
        json={
            "business_name": "Trattoria Da Luigi",
            "owner_name": "Luigi Mangione",
            "email": "luigi@daluigi.com",
            "phone": "5533445566",
            "business_type": "pizzeria",
            "plan": "pro_599",
            "menu_mode": "ai_import",
            "ai_menu_text": menu_sample,
        },
    )
    assert resp_ai.status_code == 201
    ai_data = resp_ai.json()
    assert ai_data["products_count"] >= 4

    # List all tenants
    list_resp = client.get("/api/v1/superadmin/tenants", headers=headers)
    assert list_resp.status_code == 200
    tenants = list_resp.json()
    names = [t["name"] for t in tenants]
    assert "Pizzería Nápoles" in names
    assert "Café Minimal" in names
    assert "Trattoria Da Luigi" in names


def test_superadmin_suspend_and_reactivate_tenant() -> None:
    client = _client_with_db()
    headers = _login_superadmin(client)

    # Create tenant
    create_resp = client.post(
        "/api/v1/superadmin/tenants",
        headers=headers,
        json={
            "business_name": "Taquería El Chivo",
            "owner_name": "Felipe Reyes",
            "email": "felipe@elchivo.com",
            "business_type": "taqueria",
            "plan": "starter_349",
            "menu_mode": "generate_by_type",
        },
    )
    assert create_resp.status_code == 201
    tenant_id = create_resp.json()["tenant"]["id"]

    # Suspend tenant due to non-payment
    suspend_resp = client.patch(
        f"/api/v1/superadmin/tenants/{tenant_id}/status",
        headers=headers,
        json={"status": "suspended", "reason": "Pago mensual vencido"},
    )
    assert suspend_resp.status_code == 200
    assert suspend_resp.json()["subscription_status"] == "suspended"

    # Attempt login with tenant owner should be denied
    login_resp = client.post(
        "/api/v1/auth/login",
        json={"email": "felipe@elchivo.com", "password": "Password123!"},
    )
    assert login_resp.status_code == 403
    assert login_resp.json()["detail"]["code"] == "tenant_suspended"

    # Reactivate tenant
    reactivate_resp = client.patch(
        f"/api/v1/superadmin/tenants/{tenant_id}/status",
        headers=headers,
        json={"status": "active"},
    )
    assert reactivate_resp.status_code == 200
    assert reactivate_resp.json()["subscription_status"] == "active"

    # Now login succeeds
    login_again = client.post(
        "/api/v1/auth/login",
        json={"email": "felipe@elchivo.com", "password": "Password123!"},
    )
    assert login_again.status_code == 200


def test_superadmin_impersonate_tenant() -> None:
    client = _client_with_db()
    headers = _login_superadmin(client)

    # Create tenant
    create_resp = client.post(
        "/api/v1/superadmin/tenants",
        headers=headers,
        json={
            "business_name": "Café Central",
            "owner_name": "Claudia Morales",
            "email": "claudia@cafecentral.com",
            "business_type": "cafeteria",
            "plan": "pro_599",
            "menu_mode": "generate_by_type",
        },
    )
    assert create_resp.status_code == 201
    tenant_id = create_resp.json()["tenant"]["id"]

    # Superadmin requests impersonation token
    imp_resp = client.post(
        f"/api/v1/superadmin/tenants/{tenant_id}/impersonate",
        headers=headers,
    )
    assert imp_resp.status_code == 200
    imp_data = imp_resp.json()
    assert "token" in imp_data
    assert imp_data["is_impersonating"] is True
    assert imp_data["target_email"] == "claudia@cafecentral.com"

    # Use impersonated token to fetch catalog as the customer
    customer_headers = {"Authorization": f"Bearer {imp_data['token']}"}
    cat_resp = client.get("/api/v1/catalog/products", headers=customer_headers)
    assert cat_resp.status_code == 200

    # Verify impersonation details
    assert "target_user" in imp_data
    assert imp_data["target_user"]["is_superadmin"] is False
    assert imp_data["target_user"]["email"] == "claudia@cafecentral.com"
    assert "target_branch_id" in imp_data
    assert imp_data["target_branch_id"] is not None

    # Strict multi-tenant isolation verification:
    # 1. Branches must only return Café Central's branches, NEVER 'Sucursal Piloto'
    branches_resp = client.get("/api/v1/branches", headers=customer_headers)
    assert branches_resp.status_code == 200
    branches = branches_resp.json()
    assert len(branches) == 1
    assert branches[0]["name"] == "Sucursal Matriz"
    assert branches[0]["code"] == "MATRIZ"

    # 2. Users must only return Café Central's users
    users_resp = client.get("/api/v1/users", headers=customer_headers)
    assert users_resp.status_code == 200
    users = users_resp.json()
    user_emails = [u["email"] for u in users]
    assert "claudia@cafecentral.com" in user_emails
    assert "admin@possaas.com" not in user_emails

    # 3. Roles must only return Café Central's roles
    roles_resp = client.get("/api/v1/roles", headers=customer_headers)
    assert roles_resp.status_code == 200
    roles = roles_resp.json()
    assert len(roles) >= 1


def test_superadmin_update_tenant_details() -> None:
    client = _client_with_db()
    headers = _login_superadmin(client)

    # Create tenant
    create_resp = client.post(
        "/api/v1/superadmin/tenants",
        headers=headers,
        json={
            "business_name": "Tacos El Pastor",
            "owner_name": "Juan Perez",
            "email": "juan@elpastor.com",
            "password": "Password123!",
            "business_type": "taqueria",
            "plan": "starter_349",
            "menu_mode": "generate_by_type",
        },
    )
    assert create_resp.status_code == 201
    tenant_id = create_resp.json()["tenant"]["id"]

    # Verify credentials in create response
    assert "credentials" in create_resp.json()
    assert create_resp.json()["credentials"]["email"] == "juan@elpastor.com"
    assert create_resp.json()["credentials"]["password"] == "Password123!"

    # Update all tenant details
    update_payload = {
        "name": "Tacos El Pastor Premium",
        "business_type": "taqueria",
        "owner_name": "Juan Carlos Perez",
        "owner_email": "juancarlos@elpastor.com",
        "owner_phone": "5512349999",
        "plan": "pro_599",
        "subscription_status": "active",
    }
    update_resp = client.put(
        f"/api/v1/superadmin/tenants/{tenant_id}",
        headers=headers,
        json=update_payload,
    )
    assert update_resp.status_code == 200
    updated = update_resp.json()
    assert updated["name"] == "Tacos El Pastor Premium"
    assert updated["owner_name"] == "Juan Carlos Perez"
    assert updated["owner_email"] == "juancarlos@elpastor.com"
    assert updated["owner_phone"] == "5512349999"
    assert updated["plan"] == "pro_599"
    assert updated["monthly_fee_cents"] == 59900

    # Verify login works with the updated email
    login_resp = client.post(
        "/api/v1/auth/login",
        json={"email": "juancarlos@elpastor.com", "password": "Password123!"},
    )
    assert login_resp.status_code == 200


def test_tenant_creation_has_5_canonical_roles() -> None:
    """Verify newly created tenants have exactly the 5 canonical roles in Spanish
    and owner has Administrador de Restaurante.
    """
    client = _client_with_db()
    headers = _login_superadmin(client)
    create_resp = client.post(
        "/api/v1/superadmin/tenants",
        headers=headers,
        json={
            "business_name": "Pizzeria Napoli",
            "owner_name": "Marco Rossi",
            "email": "marco@napoli.com",
            "password": "Password123!",
            "business_type": "pizzeria",
            "plan": "starter_349",
            "menu_mode": "blank",
        },
    )
    assert create_resp.status_code == 201
    owner_token = create_resp.json()["token"]
    owner_headers = {"Authorization": f"Bearer {owner_token}"}

    # Fetch tenant roles
    roles_resp = client.get("/api/v1/roles", headers=owner_headers)
    assert roles_resp.status_code == 200
    roles = roles_resp.json()
    role_names = [r["name"] for r in roles]

    assert "Cajero" in role_names
    assert "Cajero Jefe" in role_names
    assert "Líder" in role_names
    assert "Supervisor" in role_names
    assert "Administrador de Restaurante" in role_names

    # Fetch tenant users and check owner role
    users_resp = client.get("/api/v1/users", headers=owner_headers)
    assert users_resp.status_code == 200
    users = users_resp.json()
    owner = next(u for u in users if u["email"] == "marco@napoli.com")
    assert any(r["role_name"] == "Administrador de Restaurante" for r in owner.get("roles", []))


def test_superadmin_list_and_create_administrators() -> None:
    """Verify superadmin can list all restaurant administrators
    and create an independent administrator account.
    """
    client = _client_with_db()
    headers = _login_superadmin(client)

    # List administrators
    list_resp = client.get("/api/v1/superadmin/administrators", headers=headers)
    assert list_resp.status_code == 200
    admins = list_resp.json()
    assert isinstance(admins, list)

    # Create new administrator without initial restaurant
    create_admin_resp = client.post(
        "/api/v1/superadmin/administrators",
        headers=headers,
        json={
            "display_name": "Carlos Gomez",
            "email": "carlos@nuevotaqueria.com",
            "password": "Password123!",
            "phone": "5544332211",
        },
    )
    assert create_admin_resp.status_code == 201
    admin_data = create_admin_resp.json()
    assert admin_data["email"] == "carlos@nuevotaqueria.com"

    # Carlos logs in
    login_resp = client.post(
        "/api/v1/auth/login",
        json={"email": "carlos@nuevotaqueria.com", "password": "Password123!"},
    )
    assert login_resp.status_code == 200
    carlos_token = login_resp.json()["token"]
    carlos_headers = {"Authorization": f"Bearer {carlos_token}"}

    # Carlos completes self-onboarding for his restaurant
    setup_resp = client.post(
        "/api/v1/onboarding/setup-my-restaurant",
        headers=carlos_headers,
        json={
            "business_name": "Taquería El Tapatío",
            "business_type": "taqueria",
        },
    )
    assert setup_resp.status_code == 201
    setup_data = setup_resp.json()
    assert setup_data["tenant"]["name"] == "Taquería El Tapatío"
    assert setup_data["branch"]["name"] == "Sucursal Matriz"
